apiVersion: apps/v1
kind: Deployment

metadata:
  name: travel-platform-deployment


spec:
  replicas: 2

  selector:
    matchLabels:
      app: travel-platform-flask

  template:
    metadata:
      labels:
        app: travel-platform-flask

    spec:
      containers:
      - name: travel-platform-container

        image: biswarup65/travel-app-flask:v1

        ports:
        - containerPort: 5000

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"

          limits:
            memory: "256Mi"
            cpu: "200m"

        livenessProbe:
          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 10
          periodSeconds: 5