apiVersion: v1
kind: Service

metadata:
  name: travel-platform-service

spec:
  type: LoadBalancer

  selector:
    app: travel-platform-flask

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000